# Generated by Django 4.0.4 on 2022-07-06 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='genre',
            field=models.CharField(choices=[('Opinion', 'Opinion'), ('Sports', 'Sports'), ('Tech', 'Technology')], default='Opinion', max_length=300),
        ),
    ]
