# Generated by Django 4.0.4 on 2022-07-07 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_post_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='body',
            field=models.TextField(default='Mr. Anderson is working on this one.'),
        ),
    ]
